version: '3.8'
services:
  couchbase:
    image: couchbase:7.6.7
    container_name: couchbase-server
    ports:
    - 8091-8096:8091-8096
    - 11210:11210
    environment:
    - COUCHBASE_ADMINISTRATOR_USERNAME=Administrator
    - COUCHBASE_ADMINISTRATOR_PASSWORD=password
    volumes:
    - couchbase_data:/opt/couchbase/var
    healthcheck:
      test:
      - CMD
      - curl
      - -f
      - http://localhost:8091/ui/index.html
      interval: 30s
      timeout: 10s
      retries: 5
  fhir-server:
    build:
      context: ./backend
    environment:
    - SPRING_PROFILES_ACTIVE=debug
    - JAVA_OPTS=-Xms256m -Xmx1024m
    - DEPLOYED_ENV=container
    expose:
    - '8080'
    ports:
    - 8080:8080
    volumes:
    - ./config.yaml:/config.yaml:ro
    restart: unless-stopped
    depends_on:
    - keycloak
  fhir-admin:
    build:
      context: ./frontend
    expose:
    - '80'
    depends_on:
    - fhir-server
    restart: unless-stopped
  haproxy:
    image: haproxy:2.9-alpine
    ports:
    - 80:80
    volumes:
    - ./haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg:ro
    depends_on:
    - fhir-server
    restart: unless-stopped
  keycloak:
    image: quay.io/keycloak/keycloak:24.0.1
    environment:
      KEYCLOAK_ADMIN: ${KEYCLOAK_ADMIN_USERNAME}
      KEYCLOAK_ADMIN_PASSWORD: ${KEYCLOAK_ADMIN_PASSWORD}
      KC_IMPORT: 'true'
      KC_HEALTH_ENABLED: 'true'
    ports:
    - 8081:8080
    command: start-dev --http-relative-path=/auth
    restart: unless-stopped
    volumes:
    - ./scripts/keycloak/realm.json:/opt/keycloak/data/import/realm.json:ro
volumes:
  couchbase_data: {}
